print("="*6, "DESAFIO 009", "="*6)

n = int(input("Digite um Número para ver sua Tabuada: "))
print("="*20)
print("{} X  1 = {:3}".format(n, n*1))
print("{} X  2 = {:3}".format(n, n*2))
print("{} X  3 = {:3}".format(n, n*3))
print("{} X  4 = {:3}".format(n, n*4))
print("{} X  5 = {:3}".format(n, n*5))
print("{} X  6 = {:3}".format(n, n*6))
print("{} X  7 = {:3}".format(n, n*7))
print("{} X  8 = {:3}".format(n, n*8))
print("{} X  9 = {:3}".format(n, n*9))
print("{} X 10 = {:3}".format(n, n*10))
print("="*20)